packages:
  - apps/*
  - packages/config/*
  - packages/design-system/*
  - packages/testing/*
  - packages/ui/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - lefthook
  - prisma
  - sharp
