packages:
  - apps/*
  - packages/config/*
  - packages/design-system/*
  - packages/testing/*
  - packages/ui/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
