export const AUTH_SERVICE = 'AUTH_SERVICE' as const;
export const PAYMENTS_SERVICE = 'PAYMENTS_SERVICE' as const;
export const RESERVATIONS_SERVICE = 'RESERVATIONS_SERVICE' as const;
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE' as const;
